### ISSUE TITLE
WEBSITE: Announcements bar overlaps search

### ISSUE THREAD

**Issue by frkam** [feature-sliced/documentation#566]
Announcements bar overlaps search from 768 width

<img width="795" alt="Screenshot 2023-04-19 at 00 18 41" src="https://user-images.githubusercontent.com/80841256/232907386-5300310a-4cc3-4241-8aca-a845cb7a1ab0.png">

**Comment by azinit** [comment]
Thx for feedback! We'll try to fix it asap

**Comment by sldk-yuri** [comment]
@azinit  `.announcementBar` and `.DocSearch-Container` have the same `z-index`, current version used is 2.1.0, according to https://github.com/facebook/docusaurus/pull/8163 described bug have been fixed in version 2.2.0, so if you update dependency atleast up to 2.2.0 everething gonna be all right 😊

**Comment by azinit** [comment]
@sldk-yuri thank you for comment! ❤️
